[package]
name = "script_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
cooked-waker = "5.0"
bitburner_api = {path = "../bitburner_api"}

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
